### PR TITLE
Removed superfluous quote character

### PR DESCRIPTION
**Pull request by dleborgne**
Using mawk 1.3.3, percent.awk always stopped with run time error: improper conversion(number 2) in printf("%30s %'12i %6.2f%%

### CODE REVIEW

**Comment by dune73** [comment]
Everything OK with this?

**Comment by dleborgne** [comment]
Yes, thank you. After looking at https://www.gnu.org/software/gawk/manual/html_node/Format-Modifiers.html#Format-Modifiers, it seems that the printf("%'12i") syntax is a POSIX extension to ISO C that the mawk alternative to awk is unaware of.

**Comment by dune73** [comment]
Yes. I switched to gawk to be able to use the "asort" function. Other specifics might have slipped in since that moment too.

**Comment by dleborgne** [comment]
Everything is fine with GNU awk :-)

**Comment by dune73** [comment]
Are you aware that the full set of tutorials is also available in English from netnea.com? In case you prefer that...

**Comment by dleborgne** [comment]
I am currently reading the tutorials on netnea.com and cloned the git repository to get the latest version of the bin directory. Thank you for these valuable tutorials.

**Comment by dune73** [comment]
Good move. The location of the repos is a bit of a mess, I admit.
Glad you like them. I have like 5K unique visitors a month on these tutorials - but very little feedback.

In case: I'm running a 2 day Apache / ModSec course in September in Switzerland. Would not mind doing France as well if there is demand.

**Pull request closed without merging**
